In [1]:
import pandas as pd

orders = pd.read_csv("E:/Blinkit_Business_Analytics/Dataset/blinkit_orders.csv")
products = pd.read_csv("E:/Blinkit_Business_Analytics/Dataset/blinkit_products.csv")
customers = pd.read_csv("E:/Blinkit_Business_Analytics/Dataset/blinkit_customers.csv")
delivery = pd.read_csv("E:/Blinkit_Business_Analytics/Dataset/blinkit_delivery_performance.csv")
inventory = pd.read_csv("E:/Blinkit_Business_Analytics/Dataset/blinkit_inventory.csv")
feedback = pd.read_csv("E:/Blinkit_Business_Analytics/Dataset/blinkit_customer_feedback.csv")

In [2]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   str
 3   promised_delivery_time  5000 non-null   str
 4   actual_delivery_time    5000 non-null   str
 5   delivery_status         5000 non-null   str
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   str
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: float64(1), int64(4), str(5)
memory usage: 390.8 KB

In [3]:
orders.describe(include="all")

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
count,5.000000e+03,5.000000e+03,5000,5000,5000,5000,5000.00000,5000,5000.000000,5000.000000
unique,NaN,NaN,5000,4999,5000,3,NaN,4,NaN,NaN
top,NaN,NaN,2024-07-17 08:34:01,2024-10-13 14:06:50,2024-07-17 08:47:01,On Time,NaN,Card,NaN,NaN
freq,NaN,NaN,1,2,1,3470,NaN,1285,NaN,NaN
mean,5.029129e+09,5.009685e+07,NaN,NaN,NaN,NaN,2201.86170,NaN,50050.318200,4999.689000
std,2.863533e+09,2.919082e+07,NaN,NaN,NaN,NaN,1303.02438,NaN,28802.276922,2886.089242
min,6.046500e+04,3.181300e+04,NaN,NaN,NaN,NaN,13.25000,NaN,43.000000,1.000000
25%,2.531421e+09,2.404314e+07,NaN,NaN,NaN,NaN,1086.21500,NaN,24928.500000,2509.250000
50%,5.074378e+09,4.997808e+07,NaN,NaN,NaN,NaN,2100.69000,NaN,50262.500000,4987.000000
75%,7.488579e+09,7.621215e+07,NaN,NaN,NaN,NaN,3156.88250,NaN,74478.250000,7500.750000
max,9.998298e+09,9.989390e+07,NaN,NaN,NaN,NaN,6721.46000,NaN,99968.000000,9995.000000

In [4]:
orders.isnull().sum()

order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64

In [5]:
orders.duplicated().sum()

np.int64(0)

In [6]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    str
 2   category           268 non-null    str
 3   brand              268 non-null    str
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(3), int64(4), str(3)
memory usage: 21.1 KB

In [7]:
products.describe(include="all")

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
count,268.000000,268,268,268,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
unique,NaN,51,11,267,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Pet Treats,Dairy & Breakfast,Jha Group,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,12,30,2,NaN,NaN,NaN,NaN,NaN,NaN
mean,514855.940299,NaN,NaN,NaN,488.356828,680.434739,27.779851,231.757463,20.388060,74.753731
std,291391.529820,NaN,NaN,NaN,298.487200,419.772224,7.458753,151.205830,5.958546,14.591535
min,4452.000000,NaN,NaN,NaN,12.320000,17.600000,15.000000,3.000000,10.000000,50.000000
25%,273697.750000,NaN,NaN,NaN,226.717500,325.150000,20.000000,90.000000,15.000000,63.750000
50%,541459.000000,NaN,NaN,NaN,442.185000,616.970000,30.000000,365.000000,21.000000,73.000000
75%,754334.000000,NaN,NaN,NaN,779.445000,1056.620000,35.000000,365.000000,25.250000,88.000000
max,993331.000000,NaN,NaN,NaN,995.980000,1633.320000,40.000000,365.000000,30.000000,100.000000

In [8]:
products.isnull().sum()

product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

In [9]:
products.duplicated().sum()

np.int64(0)

In [10]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   str
 2   email              2500 non-null   str
 3   phone              2500 non-null   int64
 4   address            2500 non-null   str
 5   area               2500 non-null   str
 6   pincode            2500 non-null   int64
 7   registration_date  2500 non-null   str
 8   customer_segment   2500 non-null   str
 9   total_orders       2500 non-null   int64
 10  avg_order_value    2500 non-null   float64
dtypes: float64(1), int64(4), str(6)
memory usage: 215.0 KB

In [11]:
customers.describe(include="all")

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
count,2.500000e+03,2500,2500,2.500000e+03,2500,2500,2500.000000,2500,2500,2500.000000,2500.000000
unique,NaN,2491,2496,NaN,2500,316,NaN,589,4,NaN,NaN
top,NaN,Gaurang Grewal,yashoda79@example.net,NaN,"23, Nayar Path, Bihar Sharif-154625",Jalna,NaN,2024-04-22,Regular,NaN,NaN
freq,NaN,2,2,NaN,1,18,NaN,10,639,NaN,NaN
mean,4.989961e+07,NaN,NaN,9.150532e+11,NaN,NaN,497653.183200,NaN,NaN,10.491600,1102.375836
std,2.919266e+07,NaN,NaN,2.882835e+09,NaN,NaN,281167.293249,NaN,NaN,5.805533,523.043183
min,3.181300e+04,NaN,NaN,9.100132e+11,NaN,NaN,666.000000,NaN,NaN,1.000000,200.430000
25%,2.402443e+07,NaN,NaN,9.125946e+11,NaN,NaN,257079.750000,NaN,NaN,6.000000,631.817500
50%,5.000044e+07,NaN,NaN,9.150236e+11,NaN,NaN,498662.000000,NaN,NaN,10.000000,1118.650000
75%,7.595459e+07,NaN,NaN,9.176256e+11,NaN,NaN,740668.000000,NaN,NaN,16.000000,1565.400000
max,9.989390e+07,NaN,NaN,9.199988e+11,NaN,NaN,999631.000000,NaN,NaN,20.000000,1999.830000

In [12]:
customers.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

In [13]:
customers.duplicated().sum()

np.int64(0)

In [14]:
delivery.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               5000 non-null   int64
 1   delivery_partner_id    5000 non-null   int64
 2   promised_time          5000 non-null   str
 3   actual_time            5000 non-null   str
 4   delivery_time_minutes  5000 non-null   float64
 5   distance_km            5000 non-null   float64
 6   delivery_status        5000 non-null   str
 7   reasons_if_delayed     3098 non-null   str
dtypes: float64(2), int64(2), str(4)
memory usage: 312.6 KB

In [15]:
delivery.describe(include="all")

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
count,5.000000e+03,5000.000000,5000,5000,5000.000000,5000.000000,5000,3098
unique,NaN,NaN,4999,5000,NaN,NaN,3,1
top,NaN,NaN,2024-10-13 14:06:50,2024-07-17 08:47:01,NaN,NaN,On Time,Traffic
freq,NaN,NaN,2,1,NaN,NaN,3470,3098
mean,5.029129e+09,50050.318200,NaN,NaN,4.443000,2.718048,NaN,NaN
std,2.863533e+09,28802.276922,NaN,NaN,8.063929,1.290306,NaN,NaN
min,6.046500e+04,43.000000,NaN,NaN,-5.000000,0.500000,NaN,NaN
25%,2.531421e+09,24928.500000,NaN,NaN,-1.000000,1.590000,NaN,NaN
50%,5.074378e+09,50262.500000,NaN,NaN,2.000000,2.690000,NaN,NaN
75%,7.488579e+09,74478.250000,NaN,NaN,8.000000,3.850000,NaN,NaN
max,9.998298e+09,99968.000000,NaN,NaN,30.000000,5.000000,NaN,NaN

In [16]:
delivery.isnull().sum()

order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

In [17]:
delivery.duplicated().sum()

np.int64(0)

In [18]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 75172 entries, 0 to 75171
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      75172 non-null  int64
 1   date            75172 non-null  str
 2   stock_received  75172 non-null  int64
 3   damaged_stock   75172 non-null  int64
dtypes: int64(3), str(1)
memory usage: 2.3 MB

In [19]:
inventory.describe(include="all")

           product_id        date  stock_received  damaged_stock
count    75172.000000       75172    75172.000000   75172.000000
unique            NaN         600             NaN            NaN
top               NaN  04-06-2023             NaN            NaN
freq              NaN         150             NaN            NaN
mean    514290.353097         NaN        1.962513       1.067791
std     291277.971875         NaN        1.639961       0.997706
min       4452.000000         NaN        0.000000       0.000000
25%     272170.000000         NaN        0.000000       0.000000
50%     542300.000000         NaN        3.000000       2.000000
75%     753354.000000         NaN        3.000000       2.000000
max     993331.000000         NaN        4.000000       2.000000

In [20]:
inventory.isnull().sum()

product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

In [21]:
inventory.duplicated().sum()

np.int64(0)

In [22]:
feedback.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feedback_id        5000 non-null   int64
 1   order_id           5000 non-null   int64
 2   customer_id        5000 non-null   int64
 3   rating             5000 non-null   int64
 4   feedback_text      5000 non-null   str
 5   feedback_category  5000 non-null   str
 6   sentiment          5000 non-null   str
 7   feedback_date      5000 non-null   str
dtypes: int64(4), str(4)
memory usage: 312.6 KB

In [23]:
feedback.describe(include="all")

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
count,5.000000e+03,5.000000e+03,5.000000e+03,5000.00000,5000,5000,5000,5000
unique,NaN,NaN,NaN,NaN,25,4,3,600
top,NaN,NaN,NaN,NaN,The product met my expectations.,Delivery,Neutral,2024-03-31
freq,NaN,NaN,NaN,NaN,386,1271,1738,17
mean,5.013616e+06,5.029129e+09,5.009685e+07,3.34440,NaN,NaN,NaN,NaN
std,2.857341e+06,2.863533e+09,2.919082e+07,1.18982,NaN,NaN,NaN,NaN
min,9.470000e+02,6.046500e+04,3.181300e+04,1.00000,NaN,NaN,NaN,NaN
25%,2.576690e+06,2.531421e+09,2.404314e+07,3.00000,NaN,NaN,NaN,NaN
50%,5.005833e+06,5.074378e+09,4.997808e+07,4.00000,NaN,NaN,NaN,NaN
75%,7.486478e+06,7.488579e+09,7.621215e+07,4.00000,NaN,NaN,NaN,NaN
max,9.999293e+06,9.998298e+09,9.989390e+07,5.00000,NaN,NaN,NaN,NaN

In [24]:
feedback.isnull().sum()

feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

In [25]:
feedback.duplicated().sum()

np.int64(0)

### Data Cleanning

In [26]:
orders.drop_duplicates(inplace=True)
products.drop_duplicates(inplace=True) 
customers.drop_duplicates(inplace=True) 
delivery.drop_duplicates(inplace=True) 
inventory.drop_duplicates(inplace=True) 
feedback.drop_duplicates(inplace=True)

In [27]:
orders.columns = orders.columns.str.strip()
products.columns = products.columns.str.strip()
customers.columns = customers.columns.str.strip()
delivery.columns = delivery.columns.str.strip()
inventory.columns = inventory.columns.str.strip()
feedback.columns = feedback.columns.str.strip()

In [28]:
orders = orders.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
products = products.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
customers = customers.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
delivery = delivery.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
inventory = inventory.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
feedback = feedback.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

In [33]:
orders["order_date"] = pd.to_datetime(orders["order_date"])
customers["registration_date"] = pd.to_datetime(customers["registration_date"])

In [36]:
customers["address"] = customers["address"].fillna("Unknown")

In [40]:
orders.dtypes

order_id                           int64
customer_id                        int64
order_date                datetime64[us]
promised_delivery_time               str
actual_delivery_time                 str
delivery_status                      str
order_total                      float64
payment_method                       str
delivery_partner_id                int64
store_id                           int64
dtype: object

In [43]:
orders["order_total"].sum()

np.float64(11009308.5)

In [ ]:
products.head()

   product_id       date  stock_received  damaged_stock
0      153019 2023-03-17               4              2
1      848226 2023-03-17               4              2
2      965755 2023-03-17               1              0
3       39154 2023-03-17               4              0
4       34186 2023-03-17               3              2

In [47]:
inventory.head()

   product_id       date  stock_received  damaged_stock
0      153019 2023-03-17               4              2
1      848226 2023-03-17               4              2
2      965755 2023-03-17               1              0
3       39154 2023-03-17               4              0
4       34186 2023-03-17               3              2

In [49]:
orders["order_total"].describe()

count    5000.00000
mean     2201.86170
std      1303.02438
min        13.25000
25%      1086.21500
50%      2100.69000
75%      3156.88250
max      6721.46000
Name: order_total, dtype: float64

In [51]:
(products["price"] <= products["mrp"]).all()

np.True_

In [52]:
products[products["price"] > products["mrp"]]

Empty DataFrame
Columns: [product_id, product_name, category, brand, price, mrp, margin_percentage, shelf_life_days, min_stock_level, max_stock_level]
Index: []

In [53]:
delivery[delivery["delivery_time_minutes"] < 0]

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
5,3265154092,554,2023-03-18 16:49:51,2023-03-18 16:48:51,-1.0,1.94,On Time,NaN
10,4455336265,64046,2023-08-30 19:47:06,2023-08-30 19:45:06,-2.0,0.76,On Time,NaN
11,3539286337,94899,2023-04-25 20:44:24,2023-04-25 20:39:24,-5.0,3.68,On Time,NaN
...,...,...,...,...,...,...,...,...
4992,9690396315,21543,2024-09-29 11:19:50,2024-09-29 11:15:50,-4.0,3.24,On Time,NaN
4993,448732557,18718,2023-12-01 00:00:28,2023-11-30 23:58:28,-2.0,3.93,On Time,NaN
4994,4927306668,69647,2023-06-08 23:32:25,2023-06-08 23:30:25,-2.0,1.12,On Time,NaN
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,NaN
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,NaN

In [56]:
inventory[
    inventory["damaged_stock"] >
    inventory["stock_received"]
]

       product_id       date  stock_received  damaged_stock
8           14145 2023-03-17               0              2
9          847349 2023-03-17               0              2
11          77308 2023-03-17               0              2
14         217710 2023-03-17               0              2
18         741341 2023-03-17               0              2
...           ...        ...             ...            ...
75149      951463 2024-11-05               0              2
75156      771228 2024-11-05               0              2
75158      274207 2024-11-05               0              2
75162      137909 2024-11-05               0              2
75166      154179 2024-11-05               0              2

[29255 rows x 4 columns]

In [57]:
feedback[
    (feedback["rating"] < 1) |
    (feedback["rating"] > 5)
]

Empty DataFrame
Columns: [feedback_id, order_id, customer_id, rating, feedback_text, feedback_category, sentiment, feedback_date]
Index: []

In [58]:
feedback["sentiment"].value_counts()

sentiment
Neutral     1738
Negative    1642
Positive    1620
Name: count, dtype: int64

In [62]:
orders.to_csv("E:/Blinkit_Business_Analytics/Dataset/Clean_Data/orders_clean.csv", index=False)

customers.to_csv("E:/Blinkit_Business_Analytics/Dataset/Clean_Data/customers_clean.csv", index=False)

products.to_csv("E:/Blinkit_Business_Analytics/Dataset/Clean_Data/products_clean.csv", index=False)

delivery.to_csv("E:/Blinkit_Business_Analytics/Dataset/Clean_Data/delivery_clean.csv", index=False)

inventory.to_csv("E:/Blinkit_Business_Analytics/Dataset/Clean_Data/inventory_clean.csv", index=False)

feedback.to_csv("E:/Blinkit_Business_Analytics/Dataset/Clean_Data/feedback_clean.csv", index=False)